### ISSUE TITLE
FASTX.Records need a single-line representation

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/FASTX.jl#54]
A vector of records display like:
```
3-element Vector{FASTX.FASTA.Record}:
 FASTX.FASTA.Record:
   identifier: A-seg1
  description: <missing>
     sequence: AGCAAAAGCAGGTCAATTATATTCAGTATGGAAAGAATA…
 FASTX.FASTA.Record:
   identifier: A-seg2
  description: <missing>
     sequence: AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCG…
 FASTX.FASTA.Record:
   identifier: A-seg3
  description: <missing>
     sequence: AGCAAAAGCAGGTACTGATTCGAAATGGAAGATTTTGTG…
```
It would be nicer if it was something like
```
3-element Vector{FASTX.FASTA.Record}:
 FASTX.FASTA.Record("A-seg1", nothing, AGCAAAAGCAGGTCAATTATATTCAGTATGGAAAGAATA…)
 FASTX.FASTA.Record("A-seg2", nothing, AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCG…)
 FASTX.FASTA.Record("A-seg3", nothing, AGCAAAAGCAGGTACTGATTCGAAATGGAAGATTTTGTG…)
```
